version: '3.4'

networks:
  inventory-network:

services:
  webapp:
    image: inventorylight
    build:
      context: .
      dockerfile: TestCore/Dockerfile
    ports:
    - "801:80"
    networks:
    - pasta-network
    depends_on:
    - db

  db:
   image: inventorylight_db
   build:
    context: .
    dockerfile: TestCore/Dockerfile.database
   networks:
   - inventory-network
   volumes:
   - mssqldata: /var/opt/mssql

volumes:
  mssqldata
