version: '3.4'

networks:
  inventory-network:

services:
  webapp:
    environment:
    - ASPNETCORE_ENVIRONMENT=Deployment
    - DB_NAME=PastaPackages
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_PASSWORD=King.1234
    - DEPLOY=Cloud
    image: inventorylight
    build:
      context: .
      dockerfile: TestCore/Dockerfile
    ports:
    - "801:80"
    networks:
    - inventory-network
    depends_on:
    - db

  db:
   image: inventorylight_db
   build:
    context: .
    dockerfile: TestCore/Dockerfile.database
   networks:
   - inventory-network
   volumes:
   - mssqldata:/var/opt/mssql

volumes:
  mssqldata: 
